# Generated by Django 4.2 on 2023-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializari', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='specializare',
            field=models.ManyToManyField(to='specializari.specializari'),
        ),
    ]
