# Generated by Django 4.2 on 2023-04-23 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adeverinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivatie', models.CharField(max_length=1000)),
                ('numar_de_inregistrare_comun', models.IntegerField()),
                ('nr', models.IntegerField()),
                ('data', models.DateField()),
                ('acord_decan', models.BooleanField()),
                ('acord_secretar', models.BooleanField()),
                ('acord_secretar_sef', models.BooleanField()),
                ('subsemnatul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
