# Generated by Django 4.2 on 2023-04-23 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializari', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adeverinte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeverinta',
            name='decan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='decan', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adeverinta',
            name='secretar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='secretar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adeverinta',
            name='secretar_sef',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='secretar_sef', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adeverinta',
            name='specilizare',
            field=models.ManyToManyField(to='specializari.specializari'),
        ),
        migrations.AddField(
            model_name='adeverinta',
            name='stare',
            field=models.IntegerField(choices=[(0, 'ASTEPTARE'), (1, 'ACCEPTAT'), (2, 'RESPINS')], default=0),
        ),
    ]
